### ISSUE TITLE
Error: Cannot find module 'typhonjs-escomplex-commons'

### ISSUE THREAD

**Issue by acidjazz** [Qualy-org/qualy#25]
```

 ▲ ~/qualy-front gulp                                                        master :: 143d :: ⬡
[14:21:03] Using gulpfile ~/qualy-front/gulpfile.js
(node:51460) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[14:21:03] Starting 'css'...
[14:21:03] Finished 'css' after 9.29 ms
[14:21:03] Starting 'pug'...
[14:21:03] Finished 'pug' after 1.65 ms
[14:21:03] Starting 'js'...
[14:21:03] Finished 'js' after 994 μs
[14:21:03] Starting 'images'...
[14:21:03] Finished 'images' after 778 μs
[14:21:03] Starting 'watch'...
[14:21:03] Finished 'watch' after 9.65 ms
[14:21:03] Starting 'browser-sync'...
[14:21:03] Finished 'browser-sync' after 13 ms
[14:21:03] Starting 'default'...
[14:21:03] Finished 'default' after 15 μs
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.230:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.230:3001
 --------------------------------------
[BS] Serving files from: ./build/
[BS] Watching files...
resolve failed:  { Error: Cannot find module 'typhonjs-escomplex-commons'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/k/qualy-front/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/k/qualy-front/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/k/qualy-front/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/k/qualy-front/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/k/qualy-front/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/k/qualy-front/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/k/qualy-front/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } typhonjs-escomplex-commons
node_modules/nan

```

**Comment by acidjazz** [comment]
I was able to fix this by doing
```

 △ ~/qualy-front ncu                                                         master :: 143d :: ⬡
Using /Users/k/qualy-front/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠸ :
 autoprefixer-stylus          ^0.9.2  →  ^0.13.0
 babel-preset-es2015-rollup   ^1.1.1  →   ^3.0.0
 eslint                      ^2.10.0  →  ^3.18.0
 gulp-imagemin                ^2.4.0  →   ^3.1.1
 gulp-rollup                  ^1.8.0  →  ^2.11.0
 gulp-sitespeedio              0.0.8  →    1.0.0
 gulp-sourcemaps              ^1.6.0  →   ^2.4.1
 gulp-uglify                  ^1.5.3  →   ^2.1.2
 husky                       ^0.11.4  →  ^0.13.2
 jeet                         ^6.1.2  →   ^7.1.0
 kouto-swiss                 ^0.12.0  →   ^1.1.0
 rollup-plugin-commonjs       ^2.2.1  →   ^8.0.2
 rollup-plugin-node-resolve   ^1.5.0  →   ^2.0.0

Run ncu with -u to upgrade package.json

 ▲ ~/qualy-front ncu -u                                                      master :: 143d :: ⬡
```
